
services:
  db:
    container_name: "db"
    image: postgres:14.DELETE_ME_AFTER_REACT_PROJECT_CREATION-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  db_test:
    container_name: "db_test"
    image: postgres:14.DELETE_ME_AFTER_REACT_PROJECT_CREATION-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"

  react:
    build:
      context: .
      dockerfile: Dockerfiles/React
    restart: "always"
    ports:
      - "3000:3000"

  python:
    build:
      context: .
      dockerfile: Dockerfiles/Python
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: "nginx"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python
      - react
