"""Task name, planet name. Now not nullable

Revision ID: bde4acf8218c
Revises: aec50e331912
Create Date: 2023-12-13 22:52:48.194221

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bde4acf8218c'
down_revision: Union[str, None] = 'aec50e331912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    op.alter_column('task', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('planet', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    # ### end Alembic commands ###
