"""Create notifiction table

Revision ID: fe1f4915c02c
Revises: d2450c7faa8d
Create Date: 2023-11-26 17:15:04.389775

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1f4915c02c'
down_revision: Union[str, None] = 'd2450c7faa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('answer', 'accept', 'decline', 'new',
            name='notificationtype').create(op.get_bind())
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        "TIMEZONE('utc', now())"), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('type', postgresql.ENUM('answer', 'accept', 'decline', 'new',
                                                      name='notificationtype', create_type=False), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['task_id'], ['task.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    sa.Enum('answer', 'accept', 'decline', 'new',
            name='notificationtype').drop(op.get_bind())
    # ### end Alembic commands ###
