"""Delete task_difficulty, task file_link

Revision ID: dd5feffabfbf
Revises: ef1f57e34bde
Create Date: 2023-11-17 01:13:26.079539

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd5feffabfbf'
down_revision: Union[str, None] = 'ef1f57e34bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'file_link')
    op.drop_column('task', 'task_difficulty')
    sa.Enum('easy', 'medium', 'hard', name='taskdifficulty').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('easy', 'medium', 'hard',
            name='taskdifficulty').create(op.get_bind())
    op.add_column('task', sa.Column('task_difficulty', postgresql.ENUM('easy', 'medium',
                  'hard', name='taskdifficulty', create_type=False), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('file_link', sa.VARCHAR(
        length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
