"""Add planet_id column to Notification model

Revision ID: 6db5123bd673
Revises: a878e5ac62f5
Create Date: 2023-11-29 01:28:00.308091

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6db5123bd673'
down_revision: Union[str, None] = 'a878e5ac62f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column(
        'planet_id', sa.Integer(), nullable=True))
    op.alter_column('notification', 'task_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.create_foreign_key(None, 'notification', 'planet', [
                          'planet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.alter_column('notification', 'task_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_column('notification', 'planet_id')
    # ### end Alembic commands ###
