"""Modify planet table

Revision ID: a94f3a4882ee
Revises: 5e47f74aa3a2
Create Date: 2023-10-30 18:23:20.007464

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a94f3a4882ee'
down_revision: Union[str, None] = '5e47f74aa3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column(
        'curator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'planet', 'curator', [
                          'curator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'curator_id')
    # ### end Alembic commands ###
