"""Add image to Planet, Task

Revision ID: 4bc7cc6022e6
Revises: e15e45343b42
Create Date: 2023-12-07 16:03:48.437929

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc7cc6022e6'
down_revision: Union[str, None] = 'e15e45343b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('octopus1', 'octopus2', 'octopus3', 'octopus4', 'octopus5', 'octopus6',
            'octopus7', 'octopus8', 'octopus9', 'octopus10', name='taskimage').create(op.get_bind())
    sa.Enum('planet1', 'planet2', 'planet3', 'planet4', 'planet5', 'planet6', 'planet7', 'planet8',
            'planet9', 'planet10', 'planet11', 'planet12', name='planetimage').create(op.get_bind())
    op.add_column('planet', sa.Column('image', postgresql.ENUM('planet1', 'planet2', 'planet3', 'planet4', 'planet5', 'planet6',
                  'planet7', 'planet8', 'planet9', 'planet10', 'planet11', 'planet12', name='planetimage', create_type=False), nullable=False))
    op.add_column('task', sa.Column('image', postgresql.ENUM('octopus1', 'octopus2', 'octopus3', 'octopus4', 'octopus5',
                  'octopus6', 'octopus7', 'octopus8', 'octopus9', 'octopus10', name='taskimage', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'image')
    op.drop_column('planet', 'image')
    sa.Enum('planet1', 'planet2', 'planet3', 'planet4', 'planet5', 'planet6', 'planet7', 'planet8',
            'planet9', 'planet10', 'planet11', 'planet12', name='planetimage').drop(op.get_bind())
    sa.Enum('octopus1', 'octopus2', 'octopus3', 'octopus4', 'octopus5', 'octopus6',
            'octopus7', 'octopus8', 'octopus9', 'octopus10', name='taskimage').drop(op.get_bind())
    # ### end Alembic commands ###
