"""Rename product_role

Revision ID: c71512191dc0
Revises: a94f3a4882ee
Create Date: 2023-10-31 20:39:47.953016

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c71512191dc0'
down_revision: Union[str, None] = 'a94f3a4882ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('product_role', postgresql.ENUM('frontend', 'backend',
                  'analyst', 'test', 'devops', name='productrole', create_type=False), nullable=False))
    op.drop_column('employee', 'product_role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('product_role_id', postgresql.ENUM('frontend', 'backend', 'analyst',
                  'test', 'devops', name='productrole', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('employee', 'product_role')
    # ### end Alembic commands ###
