"""Edit planetImage enum

Revision ID: aec50e331912
Revises: 39c8e1b98602
Create Date: 2023-12-11 13:13:57.152964

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aec50e331912'
down_revision: Union[str, None] = '39c8e1b98602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'planetimage', ['planet1', 'planet2', 'planet3', 'planet4', 'planet5', 'planet6', 'planet7', 'planet8', 'planet9', 'planet10', 'planet11', 'planet12', 'planet13', 'planet14', 'planet15', 'planet16', 'planet17', 'planet18', 'planet19'],
                        [('planet', 'image')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'planetimage', ['planet1', 'planet2', 'planet3', 'planet4', 'planet5', 'planet6', 'planet7', 'planet8', 'planet9', 'planet10', 'planet11', 'planet12'],
                        [('planet', 'image')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
