"""Curator: curator_answer field

Revision ID: 39c8e1b98602
Revises: cdf06c3dfc1e
Create Date: 2023-12-09 14:56:30.510541

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39c8e1b98602'
down_revision: Union[str, None] = 'cdf06c3dfc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_task', sa.Column(
        'curator_answer', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_task', 'curator_answer')
    # ### end Alembic commands ###
