"""Add pos to Planet, Task

Revision ID: cdf06c3dfc1e
Revises: 4bc7cc6022e6
Create Date: 2023-12-08 16:21:28.391892

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdf06c3dfc1e'
down_revision: Union[str, None] = '4bc7cc6022e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('pos', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('pos', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'pos')
    op.drop_column('planet', 'pos')
    # ### end Alembic commands ###
