"""Create employee, curator tables, create product, productRole enums

Revision ID: 69c8745c5f06
Revises: 0b28f4052a53
Create Date: 2023-10-27 14:03:33.777757

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '69c8745c5f06'
down_revision: Union[str, None] = '0b28f4052a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curator',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('employee',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('curator_id', sa.Integer(), nullable=True),
                    sa.Column('product', sa.Enum('datapk_industrial_kit', 'industrial_firewall', 'industrial_honeypot', 'data_diode', 'itm',
                                                 'eplat4m_pass', 'eplat4m_soar', 'eplat4m_sgrc', 'eplat4m_kii', 'eplat4m', 'siem', name='product'), nullable=False),
                    sa.Column('product_role_id', sa.Enum('frontend', 'backend',
                                                         'analyst', 'test', 'devops', name='productrole'), nullable=False),
                    sa.Column('udv_coins', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['curator_id'], ['curator.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('curator')
    # ### end Alembic commands ###
