"""Rename EmployeeStatus

Revision ID: 558eb3254b30
Revises: 4e93dfe33e94
Create Date: 2023-11-05 15:37:43.474553

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '558eb3254b30'
down_revision: Union[str, None] = '4e93dfe33e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_status', postgresql.ENUM(
        'invited', 'active', name='employeestatus', create_type=False), nullable=False))
    op.drop_column('employee', 'EmployeeStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('EmployeeStatus', postgresql.ENUM(
        'invited', 'active', name='employeestatus', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('employee', 'employee_status')
    # ### end Alembic commands ###
