"""Add complete_task-count to Employee

Revision ID: 46821fdb1693
Revises: 52e21e9699ba
Create Date: 2023-12-01 18:55:03.139931

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46821fdb1693'
down_revision: Union[str, None] = '52e21e9699ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column(
        'complete_task_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'complete_task_count')
    # ### end Alembic commands ###
