"""Add employee_status enum for employee

Revision ID: 4e93dfe33e94
Revises: 3a627e8df014
Create Date: 2023-11-05 15:33:18.677256

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e93dfe33e94'
down_revision: Union[str, None] = '3a627e8df014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('invited', 'active', name='employeestatus').create(op.get_bind())
    op.add_column('employee', sa.Column('EmployeeStatus', postgresql.ENUM(
        'invited', 'active', name='employeestatus', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'EmployeeStatus')
    sa.Enum('invited', 'active', name='employeestatus').drop(op.get_bind())
    # ### end Alembic commands ###
