"""Add column employee_answer in Task table

Revision ID: 1af5ee9a3925
Revises: e1eda93d8219
Create Date: 2023-11-06 15:19:36.918415

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1af5ee9a3925'
down_revision: Union[str, None] = 'e1eda93d8219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('employee_answer',
                  sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'employee_answer')
    # ### end Alembic commands ###
