"""Notification new column: employee

Revision ID: 6a7855c44f5d
Revises: 8c1da9c4d668
Create Date: 2023-12-06 17:10:44.319530

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a7855c44f5d'
down_revision: Union[str, None] = '8c1da9c4d668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column(
        'employee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notification', 'employee', [
                          'employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'employee_id')
    # ### end Alembic commands ###
