"""Contact field for user

Revision ID: 8c1da9c4d668
Revises: 46821fdb1693
Create Date: 2023-12-05 17:03:59.025865

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c1da9c4d668'
down_revision: Union[str, None] = '46821fdb1693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'contact', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    # ### end Alembic commands ###
