"""Updated_at change

Revision ID: 76b12b48d5d7
Revises: 5d904e265853
Create Date: 2023-11-13 19:04:56.858036

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '76b12b48d5d7'
down_revision: Union[str, None] = '5d904e265853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(
    ), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'updated_at')
    # ### end Alembic commands ###
