"""Nullable name in planet

Revision ID: f12026525e0b
Revises: dd5feffabfbf
Create Date: 2023-11-17 01:46:55.365662

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f12026525e0b'
down_revision: Union[str, None] = 'dd5feffabfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('task', 'task_status',
                    existing_type=postgresql.ENUM(
                        'in_progress', 'being_checked', 'completed', name='taskstatus'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_status',
                    existing_type=postgresql.ENUM(
                        'in_progress', 'being_checked', 'completed', name='taskstatus'),
                    nullable=True)
    op.alter_column('planet', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    # ### end Alembic commands ###
