"""Task table all fields are nullable

Revision ID: 5d904e265853
Revises: 1af5ee9a3925
Create Date: 2023-11-13 00:42:14.032952

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d904e265853'
down_revision: Union[str, None] = '1af5ee9a3925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('task', 'description',
                    existing_type=sa.VARCHAR(length=1000),
                    type_=sa.String(length=10000),
                    nullable=True)
    op.alter_column('task', 'task_status',
                    existing_type=postgresql.ENUM(
                        'in_progress', 'being_checked', 'completed', name='taskstatus'),
                    nullable=True)
    op.alter_column('task', 'task_difficulty',
                    existing_type=postgresql.ENUM(
                        'easy', 'medium', 'hard', name='taskdifficulty'),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_difficulty',
                    existing_type=postgresql.ENUM(
                        'easy', 'medium', 'hard', name='taskdifficulty'),
                    nullable=False)
    op.alter_column('task', 'task_status',
                    existing_type=postgresql.ENUM(
                        'in_progress', 'being_checked', 'completed', name='taskstatus'),
                    nullable=False)
    op.alter_column('task', 'description',
                    existing_type=sa.String(length=10000),
                    type_=sa.VARCHAR(length=1000),
                    nullable=False)
    op.alter_column('task', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    # ### end Alembic commands ###
