"""Add id for employee_task

Revision ID: 55865d016bbe
Revises: d2450c7faa8d
Create Date: 2023-11-19 19:27:58.506096

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '55865d016bbe'
down_revision: Union[str, None] = 'd2450c7faa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_task', sa.Column(
        'id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_task', 'id')
    # ### end Alembic commands ###
