"""Enum notificationType new field: invited

Revision ID: a878e5ac62f5
Revises: fe1f4915c02c
Create Date: 2023-11-29 01:14:15.623655

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a878e5ac62f5'
down_revision: Union[str, None] = 'fe1f4915c02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'notificationtype', ['answer', 'accept', 'decline', 'new', 'invited'],
                        [('notification', 'type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'notificationtype', ['answer', 'accept', 'decline', 'new'],
                        [('notification', 'type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
