# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres_test:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres_test
          POSTGRES_PASSWORD: postgres_test
          POSTGRES_DB: postgres_test
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create env file
      run: |
        touch .env
        echo POSTGRES='postgresql+asyncpg://postgres:postgres@db:5432/postgres' >> .env
        echo POSTGRES_TEST='postgresql+asyncpg://postgres_test:postgres_test@db_test/postgres_test' >> .env
        echo SECRET='no_secret_key_here' >> .env
        cat .env

    - name: Test with pytest
      run: |
        pytest
